## Today Topic
- Random Forest Model

### Random Forest Model
- Random forest algorithm is one of the Ensemble Technique.
- Ensemble method will split data into multiple parts and then combine them to produce improved results.
- Collection of Decision tree models is called a Random Forest Model. (Random forest is similar to Decision tree.)
- Random Forest plays a key role for huge dataset. (lakhs of rows and 100s of columns)
- Applicable for both classification and regression model

### Working of Random Forest model
- Step1: Selection of random samples in given dataset
- Step2: It will apply Decision Tree model for every sample.
- Step3: It will get the prediction result for every decision tree. And voyeing will be performed.
- Step4: Majority voted prediction result will be taken as final prediction result.
- Eg:
    - Training Sample1 --> Female
    - Training Sample2 --> Male
    - Training SampleN --> Male
    - 'Majority voted is Male'

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/nagamounika5/Datasets/master/diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.shape

(768, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
Pregnancies                 768 non-null int64
Glucose                     768 non-null int64
BloodPressure               768 non-null int64
SkinThickness               768 non-null int64
Insulin                     768 non-null int64
BMI                         768 non-null float64
DiabetesPedigreeFunction    768 non-null float64
Age                         768 non-null int64
Outcome                     768 non-null int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [6]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
df.isnull().sum().sum()

0

In [8]:
X = df.drop('Outcome', axis = 1) ## Input variable
Y = df['Outcome']    ## Target variable

In [9]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [10]:
Y[:5]

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.30, random_state = 45)

In [12]:
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
172,2,87,0,23,0,28.9,0.773,25
405,2,123,48,32,165,42.1,0.520,26
357,13,129,0,30,0,39.9,0.569,44
483,0,84,82,31,125,38.2,0.233,23
738,2,99,60,17,160,36.6,0.453,21
69,4,146,85,27,100,28.9,0.189,27
515,3,163,70,18,105,31.6,0.268,28
726,1,116,78,29,180,36.1,0.496,25
344,8,95,72,0,0,36.8,0.485,57
611,3,174,58,22,194,32.9,0.593,36
469,6,154,78,41,140,46.1,0.571,27
676,9,156,86,0,0,24.8,0.230,53
227,3,162,52,38,0,37.2,0.652,24
562,1,87,68,34,77,37.6,0.401,24
179,5,130,82,0,0,39.1,0.956,37
618,9,112,82,24,0,28.2,1.282,50
349,5,0,80,32,0,41.0,0.346,37
274,13,106,70,0,0,34.2,0.251,52
204,6,103,72,32,190,37.7,0.324,55
659,3,80,82,31,70,34.2,1.292,27
579,2,197,70,99,0,34.7,0.575,62
381,0,105,68,22,0,20.0,0.236,22
230,4,142,86,0,0,44.0,0.645,22
249,1,111,86,19,0,30.1,0.143,23
504,3,96,78,39,0,37.3,0.238,40
645,2,157,74,35,440,39.4,0.134,30
724,1,111,94,0,0,32.8,0.265,45
103,1,81,72,18,40,26.6,0.283,24
131,9,122,56,0,0,33.3,1.114,33
710,3,158,64,13,387,31.2,0.295,24
...,...,...,...,...,...,...,...,...
36,11,138,76,0,0,33.2,0.420,35
490,2,83,65,28,66,36.8,0.629,24
270,10,101,86,37,0,45.6,1.136,38
158,2,88,74,19,53,29.0,0.229,22
638,7,97,76,32,91,40.9,0.871,32
110,3,171,72,33,135,33.3,0.199,24
196,1,105,58,0,0,24.3,0.187,21
486,1,139,62,41,480,40.7,0.536,21
17,7,107,74,0,0,29.6,0.254,31
268,0,102,52,0,0,25.1,0.078,21
24,11,143,94,33,146,36.6,0.254,51
380,1,107,72,30,82,30.8,0.821,24
181,0,119,64,18,92,34.9,0.725,23
264,4,123,62,0,0,32.0,0.226,35
215,12,151,70,40,271,41.8,0.742,38
456,1,135,54,0,0,26.7,0.687,62
569,0,121,66,30,165,34.3,0.203,33
309,2,124,68,28,205,32.9,0.875,30
398,3,82,70,0,0,21.1,0.389,25
577,2,118,80,0,0,42.9,0.693,21
15,7,100,0,0,0,30.0,0.484,32
632,2,111,60,0,0,26.2,0.343,23
377,1,87,60,37,75,37.2,0.509,22
580,0,151,90,46,0,42.1,0.371,21
163,2,100,64,23,0,29.7,0.368,21
725,4,112,78,40,0,39.4,0.236,38
607,1,92,62,25,41,19.5,0.482,25
544,1,88,78,29,76,32.0,0.365,29
643,4,90,0,0,0,28.0,0.610,31
414,0,138,60,35,167,34.6,0.534,21

In [14]:
X_train.shape , X_test.shape

((537, 8), (231, 8))

In [15]:
Y_train.shape, Y_test.shape

((537,), (231,))

In [16]:
### Apply Random forest model

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
rfc = RandomForestClassifier()
rfc

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators='warn',
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [19]:
rfc.fit(X_train, Y_train)

C:\Users\Mouni\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [20]:
Y_prediction = rfc.predict(X_test)
Y_prediction

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [21]:
X_test.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
195,5,158,84,41,210,39.4,0.395,29
51,1,101,50,15,36,24.2,0.526,26
66,0,109,88,30,0,32.5,0.855,38

In [22]:
Y[:3]

0    1
1    0
2    1
Name: Outcome, dtype: int64

In [24]:
rfc.predict([[5, 158, 84, 41, 210, 39.4, 0.395, 29]])

array([0], dtype=int64)

In [25]:
rfc.predict([[1, 101, 50, 15, 36, 24.2, 0.526, 26]])

array([0], dtype=int64)

In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_prediction, Y_test)

array([[134,  41],
       [ 20,  36]], dtype=int64)

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_prediction, Y_test)

0.7359307359307359

#### Task: 
- https://raw.githubusercontent.com/nagamounika5/Datasets/master/Glass_Classification.csv
- Apply Random forest model to above dataset.